name: CI

# This workflow runs on pushes and pull requests to the main and dev branches.
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - dev

env:
  STEP_TIMEOUT_MINUTES: 60

jobs:
  smoke_test:
    name: Smoke Test (Debug Build of Zenith.App)
    # This job runs ONLY on pushes to the 'main' branch (e.g., after a PR is merged).
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Caches dependencies to speed up subsequent workflow runs.
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.nuget/packages
            ~/.dotnet/packs
            ~/.dotnet/workload-packs
          # The cache is invalidated when package versions or the SDK version changes.
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/Directory.Packages.props', '**/global.json') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-

      - name: Install Dependencies
        timeout-minutes: ${{ fromJSON(env.STEP_TIMEOUT_MINUTES) }}
        uses: "./.github/steps/install_dependencies"

      # Build the desktop head of the app using the dotnet CLI.
      - name: Build Zenith.App (Debug)
        shell: pwsh
        run: dotnet build ./Zenith.App/Zenith.App.csproj -f net9.0-desktop -c Debug

  unit_test:
    name: Unit Tests
    # This job runs on pushes to 'dev' AND on pull requests targeting 'main'.
    if: (github.event_name == 'push' && github.ref == 'refs/heads/dev') || (github.event_name == 'pull_request' && github.base_ref == 'main')
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Caches dependencies to speed up subsequent workflow runs.
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.nuget/packages
            ~/.dotnet/packs
            ~/.dotnet/workload-packs
          # The cache is invalidated when package versions or the SDK version changes.
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/Directory.Packages.props', '**/global.json') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-

      - name: Install Dependencies
        timeout-minutes: ${{ fromJSON(env.STEP_TIMEOUT_MINUTES) }}
        uses: "./.github/steps/install_dependencies"

      # Build and run the unit tests using the dotnet CLI.
      # The `dotnet test` command automatically restores and builds the project.
      - name: Run Unit Tests
        shell: pwsh
        run: dotnet test ./Zenith.App.Tests/Zenith.App.Tests.csproj -c Release -f net9.0-desktop --logger GitHubActions --blame-crash --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
